sudo: false

notifications:
  email:
    - evantahler@gmail.com
language: node_js
node_js:
  - "4.0"
  - "6.0"

branches:
  only:
    - master
services:
  - redis-server
# before_script:
notifications:
